//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthServiceProvider_Details
    {
        public int Id { get; set; }
        public string F_Name { get; set; }
        public string L_Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string HospitalName { get; set; }
        public string Specialization { get; set; }
        public string Designation { get; set; }
        public string Workplace_Location_Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
    }
}
