//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthServiceProvider_Day_Details
    {
        public int Id { get; set; }
        public int HealthServiceProvider_ID { get; set; }
        public string Specialization { get; set; }
        public string HealthServiceProvider_Name { get; set; }
        public string HealthServiceProvider_Address { get; set; }
    }
}
